[package]
name = "alds_1_11_c"
version = "0.1.0"
authors = ["Takahiro Kawashige <lapavoni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
